services:
  emagrecimento:
    build: .
    container_name: emagrecimento
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - npm_network

networks:
  npm_network:
    name: npm_network
    external: true
